package InicioSesion;

import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;

public class crearCuenta extends javax.swing.JFrame {

    public crearCuenta() {
        getContentPane().setBackground(new Color(0, 0, 0));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearCuenta = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        tituloLogin = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        labelContrasena = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        panelBotones = new javax.swing.JPanel();
        botonNuevaCuenta = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(146, 10, 8));
        setPreferredSize(new java.awt.Dimension(380, 170));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        panelCrearCuenta.setBackground(new java.awt.Color(16, 28, 62));
        panelCrearCuenta.setPreferredSize(new java.awt.Dimension(380, 170));
        panelCrearCuenta.setLayout(new java.awt.BorderLayout());

        panelTitulo.setBackground(getBackground());

        tituloLogin.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloLogin.setForeground(new java.awt.Color(254, 254, 254));
        tituloLogin.setText("Nueva cuenta");
        panelTitulo.add(tituloLogin);

        panelCrearCuenta.add(panelTitulo, java.awt.BorderLayout.NORTH);

        panelDatos.setBackground(getBackground());
        panelDatos.setPreferredSize(new java.awt.Dimension(200, 150));
        panelDatos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        labelUsuario.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(254, 254, 254));
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsuario.setText("Usuario:");
        labelUsuario.setPreferredSize(new java.awt.Dimension(100, 30));
        panelDatos.add(labelUsuario);

        textUsuario.setColumns(13);
        textUsuario.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        panelDatos.add(textUsuario);

        labelContrasena.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        labelContrasena.setForeground(new java.awt.Color(254, 254, 254));
        labelContrasena.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelContrasena.setText("Contraseña:");
        labelContrasena.setPreferredSize(new java.awt.Dimension(100, 30));
        panelDatos.add(labelContrasena);

        textPassword.setColumns(13);
        textPassword.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        panelDatos.add(textPassword);

        panelBotones.setBackground(getBackground());
        panelBotones.setPreferredSize(new java.awt.Dimension(380, 50));

        botonNuevaCuenta.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        botonNuevaCuenta.setText("Crear cuenta");
        botonNuevaCuenta.setName("nuevo"); // NOI18N
        botonNuevaCuenta.setPreferredSize(new java.awt.Dimension(120, 30));
        botonNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaCuentaActionPerformed(evt);
            }
        });
        panelBotones.add(botonNuevaCuenta);

        botonCancelar.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setName("cancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelar);

        panelDatos.add(panelBotones);

        panelCrearCuenta.add(panelDatos, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCrearCuenta);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaCuentaActionPerformed

        Conexion conn = new Conexion();
        String usuario = textUsuario.getText();
        String password = new String(textPassword.getPassword());
        conn.enviarMensaje("NuevaCuenta " + usuario + " " + password);
        System.out.println("Envié el mensaje");
        try {
            String mensaje = conn.recibirMensaje();
            System.out.println("Mensaje: " + mensaje);
            if(mensaje.equals("OK")){
                int res = JOptionPane.showOptionDialog(null, "Cuenta de usuario creada", "",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                this.dispose();
            } else{
                int res = JOptionPane.showOptionDialog(null, "El nombre de usuario ya existe", "",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
            }
        } catch (IOException ex) {}
    }//GEN-LAST:event_botonNuevaCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new crearCuenta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonNuevaCuenta;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCrearCuenta;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsuario;
    private javax.swing.JLabel tituloLogin;
    // End of variables declaration//GEN-END:variables
}
